{% set version = "0.3.8" %}

package:
  name: mosdepth
  version: {{ version }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("mosdepth", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - curl
    - rsync
  host:
    - htslib >=1.19.1
  run:
    - {{ c_compiler }}_{{ target_platform }}
    - {{ cxx_compiler }}_{{ target_platform }}

test:
  commands:
    - mosdepth -h

about:
  home: https://github.com/brentp/mosdepth
  dev_url: https://github.com/brentp/mosdepth
  doc_url: https://github.com/brentp/mosdepth
  license: MIT
  summary: 'Fast BAM/CRAM depth calculation for WGS, exome, or targeted sequencing.'

extra:
  identifiers:
    - doi:10.1093/bioinformatics/btx699
    - biotools:mosdepth
