{% set version = "0.3.8" %}

package:
  name: mosdepth
  version: {{ version }}

source:
  - url: https://github.com/nim-lang/nightlies/archive/refs/tags/2024-04-24-version-1-6-b7b3f87719a201007e5dc0730bf73141fd908c6a.zip
    sha256 : 8422cefd574686bfd4741a1e7c6dbf247dc4701ba7e0b2afe968664719c39bc8
    folder : extlibs/nim

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("mosdepth", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - curl
  host:
    - htslib >=1.19.1
  run:

test:
  commands:
    - mosdepth -h

about:
  home: https://github.com/brentp/mosdepth
  dev_url: https://github.com/brentp/mosdepth
  doc_url: https://github.com/brentp/mosdepth
  license: MIT
  summary: 'Fast BAM/CRAM depth calculation for WGS, exome, or targeted sequencing.'

extra:
  identifiers:
    - doi:10.1093/bioinformatics/btx699
    - biotools:mosdepth
